# Generated by Django 5.2.8 on 2026-01-14 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Gmail account synced",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("last_sync", models.DateTimeField(auto_now=True)),
                (
                    "history_id",
                    models.CharField(
                        blank=True,
                        help_text="Gmail history ID for incremental sync",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("in_progress", "In Progress"),
                        ],
                        default="success",
                        max_length=50,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "emails_synced",
                    models.IntegerField(
                        default=0, help_text="Number of emails synced in last sync"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Status",
                "verbose_name_plural": "Sync Statuses",
                "ordering": ["-last_sync"],
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_email",
                    models.EmailField(
                        db_index=True,
                        help_text="Gmail account this email belongs to",
                        max_length=255,
                    ),
                ),
                (
                    "gmail_id",
                    models.CharField(
                        help_text="Gmail message ID", max_length=255, unique=True
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        db_index=True, help_text="Gmail thread ID", max_length=255
                    ),
                ),
                ("subject", models.TextField(blank=True)),
                ("sender", models.EmailField(max_length=255)),
                (
                    "sender_name",
                    models.CharField(
                        blank=True, help_text="Sender's display name", max_length=255
                    ),
                ),
                ("recipient", models.EmailField(blank=True, max_length=255)),
                (
                    "cc",
                    models.TextField(
                        blank=True, help_text="CC recipients (comma-separated)"
                    ),
                ),
                (
                    "bcc",
                    models.TextField(
                        blank=True, help_text="BCC recipients (comma-separated)"
                    ),
                ),
                ("date", models.DateTimeField(db_index=True)),
                (
                    "snippet",
                    models.TextField(blank=True, help_text="Email preview text"),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, help_text="Plain text body"),
                ),
                ("body_html", models.TextField(blank=True, help_text="HTML body")),
                (
                    "labels",
                    models.JSONField(
                        default=list, help_text="Gmail labels (INBOX, SENT, etc.)"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("has_attachments", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="gmail_integ_date_33c000_idx"),
                    models.Index(
                        fields=["thread_id"], name="gmail_integ_thread__5917cc_idx"
                    ),
                    models.Index(
                        fields=["account_email", "-date"],
                        name="gmail_integ_account_b4d619_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_account",
                    models.EmailField(
                        help_text="Gmail address (e.g., support@godamwale.com)",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "token_data",
                    models.JSONField(
                        help_text="Stores access token, refresh token, and expiry"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this account is actively syncing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="ERP user who owns this token",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gmail Token",
                "verbose_name_plural": "Gmail Tokens",
                "unique_together": {("user", "email_account")},
            },
        ),
    ]
