# Generated by Django 5.2.8 on 2026-01-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gmailtoken",
            name="email_account",
            field=models.EmailField(
                db_index=True,
                help_text="Gmail address (e.g., support@godamwale.com)",
                max_length=254,
            ),
        ),
    ]
