# Generated by Django 5.2.8 on 2026-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0002_alter_gmailtoken_email_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailtoken",
            name="account_color",
            field=models.CharField(
                default="account-gray",
                help_text="CSS class for account color (e.g., account-purple)",
                max_length=50,
            ),
        ),
    ]
