# Generated by Django 5.2.8 on 2026-01-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0003_gmailtoken_account_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["email"],
            },
        ),
        migrations.AddField(
            model_name="email",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="All recipients (To, CC, BCC)",
                related_name="received_emails",
                to="gmail_integration.contact",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="sender_contact",
            field=models.ForeignKey(
                help_text="Link to Sender Contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails",
                to="gmail_integration.contact",
            ),
        ),
    ]
