# Generated by Django 5.2.8 on 2026-01-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0006_migrate_legacy_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="bcc",
        ),
        migrations.RemoveField(
            model_name="email",
            name="cc",
        ),
        migrations.RemoveField(
            model_name="email",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="email",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="email",
            name="sender_name",
        ),
    ]
