# Generated by Django 5.2.8 on 2026-01-15 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0007_remove_email_bcc_remove_email_cc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="account_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the Gmail Token/Account",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="emails",
                to="gmail_integration.gmailtoken",
            ),
        ),
    ]
