# Generated by Django 5.2.8 on 2026-01-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0008_email_account_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gmail_attachment_id",
                    models.CharField(help_text="Gmail's attachment ID", max_length=255),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "mime_type",
                    models.CharField(
                        help_text="File MIME type (e.g., application/pdf)",
                        max_length=100,
                    ),
                ),
                ("size_bytes", models.IntegerField(help_text="File size in bytes")),
                (
                    "file",
                    models.FileField(
                        help_text="Stored file", upload_to="attachments/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        help_text="Email this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="gmail_integration.email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["filename"],
                "indexes": [
                    models.Index(
                        fields=["email", "filename"],
                        name="gmail_integ_email_i_bd0ea3_idx",
                    )
                ],
            },
        ),
    ]
