# Generated by Django 5.2.8 on 2026-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0009_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailtoken",
            name="encrypted_token_data",
            field=models.TextField(
                blank=True, help_text="Encrypted token data (GDPR compliant)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="gmailtoken",
            name="token_data",
            field=models.JSONField(
                blank=True,
                help_text="Stores access token, refresh token, and expiry",
                null=True,
            ),
        ),
    ]
