# Generated by Antigravity
from django.db import migrations

def encrypt_tokens(apps, schema_editor):
    GmailToken = apps.get_model('gmail_integration', 'GmailToken')
    from gmail_integration.utils.encryption import EncryptionUtils
    
    tokens = GmailToken.objects.all()
    count = 0
    for token in tokens:
        if token.token_data and not token.encrypted_token_data:
            # Encrypt the plaintext data
            encrypted = EncryptionUtils.encrypt(token.token_data)
            token.encrypted_token_data = encrypted
            token.save()
            count += 1
            print(f"Encrypted token for {token.email_account}")
    print(f"Total tokens encrypted: {count}")

def reverse_encrypt(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0010_gmailtoken_encrypted_token_data_and_more'),
    ]

    operations = [
        migrations.RunPython(encrypt_tokens, reverse_encrypt),
    ]
