# Generated by Django 5.2.8 on 2026-01-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmail_integration", "0011_encrypt_existing_tokens"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gmailtoken",
            options={
                "permissions": [
                    ("view_all_gmail_accounts", "Can view all Gmail accounts")
                ],
                "verbose_name": "Gmail Token",
                "verbose_name_plural": "Gmail Tokens",
            },
        ),
    ]
